import {FiLink} from 'react-icons/fi'
import './drop-down.style.css';

const DropDown = ({top , dropDown ,setBackgroundUrl,backgroundUrl ,setColorOpacity , colorOpacity ,setBackgroundOpacity, backgroundOpacity,setWidth, width , setHeight , height}) => {
    return (
        <>
            {
                dropDown === 1 ?
                    <table className='drop-down' style={{top}}>
                        <thead>
                            <tr>
                                <th>Tex Command</th>
                                <th>Operator</th>
                            </tr>    
                        </thead>
                        <tbody>
                            <tr>
                                <td>+</td>
                                <td>+</td>
                            </tr>
                            <tr>
                                <td>-</td>
                                <td>-</td>
                            </tr>
                            <tr>
                                <td>=</td>
                                <td>=</td>
                            </tr>
                            <tr>
                                <td>&gt;</td>
                                <td>&gt;</td>
                            </tr>
                            <tr>
                                <td>&lt;</td>
                                <td>&lt;</td>
                            </tr>
                            <tr>
                                <td>|</td>
                                <td>|</td>
                            </tr>
                            <tr>
                                <td>%</td>
                                <td>%</td>
                            </tr>
                            <tr>
                                <td>,</td>
                                <td>,</td>
                            </tr>
                            <tr>
                                <td>.</td>
                                <td>.</td>
                            </tr>
                            <tr>
                                <td>$</td>
                                <td>$</td>
                            </tr>
                            <tr>
                                <td>(</td>
                                <td>(</td>
                            </tr>
                            <tr>
                                <td>)</td>
                                <td>)</td>
                            </tr>
                            <tr>
                                <td>[</td>
                                <td>[</td>
                            </tr>
                            <tr>
                                <td>]</td>
                                <td>]</td>
                            </tr>
                            <tr>
                                <td>!</td>
                                <td>!</td>
                            </tr>
                            <tr>
                                <td>\leq</td>
                                <td>≤</td>
                            </tr>
                            <tr>
                                <td>\geq</td>
                                <td>≥</td>
                            </tr>
                            <tr>
                                <td>\ll</td>
                                <td>≪</td>
                            </tr>
                            <tr>
                                <td>\gg</td>
                                <td>≫</td>
                            </tr>
                            <tr>
                                <td>\subset</td>
                                <td>⊂</td>
                            </tr>
                            <tr>
                                <td>\supset</td>
                                <td>⊃</td>
                            </tr>
                            <tr>
                                <td>\subseteq</td>
                                <td>⊆</td>
                            </tr>
                            <tr>
                                <td>\supseteq</td>
                                <td>⊇</td>
                            </tr>
                            <tr>
                                <td>\nsubseteq</td>
                                <td>⊈</td>
                            </tr>
                            <tr>
                                <td>\nsupseteq</td>
                                <td>⊉</td>
                            </tr>
                            <tr>
                                <td>\sqsubset</td>
                                <td>⊏</td>
                            </tr>
                            <tr>
                                <td>\sqsupset</td>
                                <td>⊐</td>
                            </tr>
                            <tr>
                                <td>\sqsubseteq</td>
                                <td>⊑</td>
                            </tr>
                            <tr>
                                <td>\sqsupseteq</td>
                                <td>⊒</td>
                            </tr>
                            <tr>
                                <td>\preceq</td>
                                <td>⪯</td>
                            </tr>
                            <tr>
                                <td>\succeq</td>
                                <td>⪰</td>
                            </tr>
                            <tr>
                                <td>\doteq</td>
                                <td>≐</td>
                            </tr>
                            <tr>
                                <td>\equiv</td>
                                <td>≡</td>
                            </tr>
                            <tr>
                                <td>\approx</td>
                                <td>≈</td>
                            </tr>
                            <tr>
                                <td>\cong</td>
                                <td>≅</td>
                            </tr>
                            <tr>
                                <td>\simeq</td>
                                <td>≃</td>
                            </tr>
                            <tr>
                                <td>\sim</td>
                                <td>∼</td>
                            </tr>
                            <tr>
                                <td>\propto</td>
                                <td>∝</td>
                            </tr>
                            <tr>
                                <td>\neq</td>
                                <td>≠</td>
                            </tr>
                            <tr>
                                <td>\parallel</td>
                                <td>∥</td>
                            </tr>
                            <tr>
                                <td>\asymp</td>
                                <td>≍</td>
                            </tr>
                            <tr>
                                <td>\vdash</td>
                                <td>⊢</td>
                            </tr>
                            <tr>
                                <td>\in</td>
                                <td>∈</td>
                            </tr>
                            <tr>
                                <td>\smile</td>
                                <td>⌣</td>
                            </tr>
                            <tr>
                                <td>\models</td>
                                <td>⊨</td>
                            </tr>
                            <tr>
                                <td>\perp</td>
                                <td>⊥</td>
                            </tr>
                            <tr>
                                <td>\prec</td>
                                <td>≺</td>
                            </tr>
                            <tr>
                                <td>\sphericalangle</td>
                                <td>∢</td>
                            </tr>
                            <tr>
                                <td>\nparallel</td>
                                <td>∦</td>
                            </tr>
                            <tr>
                                <td>\bowtie</td>
                                <td>⋈</td>
                            </tr>
                            <tr>
                                <td>\dashv</td>
                                <td>⊣</td>
                            </tr>
                            <tr>
                                <td>\ni</td>
                                <td>∋</td>
                            </tr>
                            <tr>
                                <td>\frown</td>
                                <td>⌢</td>
                            </tr>
                            <tr>
                                <td>\notin</td>
                                <td>∉</td>
                            </tr>
                            <tr>
                                <td>\mid</td>
                                <td>∣</td>
                            </tr>
                            <tr>
                                <td>\succ</td>
                                <td>≻</td>
                            </tr>
                            <tr>
                                <td>\measuredangle</td>
                                <td>∡</td>
                            </tr>
                            <tr>
                                <td>\pm</td>
                                <td>±</td>
                            </tr>
                            <tr>
                                <td>\div</td>
                                <td>÷</td>
                            </tr>
                            <tr>
                                <td>\times</td>
                                <td>×</td>
                            </tr>
                            <tr>
                                <td>\cdot</td>
                                <td>⋅</td>
                            </tr>
                            <tr>
                                <td>\mp</td>
                                <td>∓</td>
                            </tr>
                            <tr>
                                <td>\ast</td>
                                <td>∗</td>
                            </tr>
                            <tr>
                                <td>\star</td>
                                <td>⋆</td>
                            </tr>
                            <tr>
                                <td>\dagger</td>
                                <td>†</td>
                            </tr>
                            <tr>
                                <td>\ddagger</td>
                                <td>‡</td>
                            </tr>
                            <tr>
                                <td>\cap</td>
                                <td>∩</td>
                            </tr>
                            <tr>
                                <td>\cup</td>
                                <td>∪</td>
                            </tr>
                            <tr>
                                <td>\uplus</td>
                                <td>⊎</td>
                            </tr>
                            <tr>
                                <td>\sqcap</td>
                                <td>⊓</td>
                            </tr>
                            <tr>
                                <td>\sqcup</td>
                                <td>⊔</td>
                            </tr>
                            <tr>
                                <td>\vee</td>
                                <td>∨</td>
                            </tr>
                            <tr>
                                <td>\wedge</td>
                                <td>∧</td>
                            </tr>
                            <tr>
                                <td>\diamond</td>
                                <td>⋄</td>
                            </tr>
                            <tr>
                                <td>\bigtriangleup</td>
                                <td>△</td>
                            </tr>
                            <tr>
                                <td>\bigtriangledown</td>
                                <td>▽</td>
                            </tr>
                            <tr>
                                <td>\triangleleft</td>
                                <td>◃</td>
                            </tr>
                            <tr>
                                <td>\triangleright</td>
                                <td>▹</td>
                            </tr>
                            <tr>
                                <td>\bigcirc</td>
                                <td>◯</td>
                            </tr>
                            <tr>
                                <td>\bullet</td>
                                <td>∙</td>
                            </tr>
                            <tr>
                                <td>\wr</td>
                                <td>≀</td>
                            </tr>
                            <tr>
                                <td>\oplus</td>
                                <td>⊕</td>
                            </tr>
                            <tr>
                                <td>\ominus</td>
                                <td>⊖</td>
                            </tr>
                            <tr>
                                <td>\otimes</td>
                                <td>⊗</td>
                            </tr>
                            <tr>
                                <td>\odot</td>
                                <td>⊙</td>
                            </tr>
                            <tr>
                                <td>\circ</td>
                                <td>∘</td>
                            </tr>
                            <tr>
                                <td>\setminus</td>
                                <td>∖</td>
                            </tr>
                            <tr>
                                <td>\amalg</td>
                                <td>⨿</td>
                            </tr>
                            <tr>
                                <td>\exists</td>
                                <td>∃</td>
                            </tr>
                            <tr>
                                <td>\nexists</td>
                                <td>∄</td>
                            </tr>
                            <tr>
                                <td>\forall</td>
                                <td>∀</td>
                            </tr>
                            <tr>
                                <td>\neg</td>
                                <td>¬</td>
                            </tr>
                            <tr>
                                <td>\land</td>
                                <td>∧</td>
                            </tr>
                            <tr>
                                <td>\lor</td>
                                <td>∨</td>
                            </tr>
                            <tr>
                                <td>\rightarrow</td>
                                <td>→</td>
                            </tr>
                            <tr>
                                <td>\leftarrow</td>
                                <td>←</td>
                            </tr>
                            <tr>
                                <td>\mapsto</td>
                                <td>↦</td>
                            </tr>
                            <tr>
                                <td>\implies</td>
                                <td>⟹</td>
                            </tr>
                            <tr>
                                <td>\Rightarrow</td>
                                <td>⇒</td>
                            </tr>
                            <tr>
                                <td>\leftrightarrow</td>
                                <td>↔</td>
                            </tr>
                            <tr>
                                <td>\iff</td>
                                <td>⟺</td>
                            </tr>
                            <tr>
                                <td>\Leftrightarrow</td>
                                <td>⇔</td>
                            </tr>
                            <tr>
                                <td>\top</td>
                                <td>⊤</td>
                            </tr>
                            <tr>
                                <td>\bot</td>
                                <td>⊥</td>
                            </tr>
                            <tr>
                                <td>\emptyset</td>
                                <td>∅</td>
                            </tr>
                            <tr>
                                <td>\varnothing</td>
                                <td>∅</td>
                            </tr>
                            <tr>
                                <td>{'\\{'}</td>
                                <td>{'{'}</td>
                            </tr>
                            <tr>
                                <td>\uparrow</td>
                                <td>↑</td>
                            </tr>
                            <tr>
                                <td>\downarrow</td>
                                <td>↓</td>
                            </tr>
                            <tr>
                                <td>\|</td>
                                <td>‖</td>
                            </tr>
                            <tr>
                                <td>{'\\}'}</td>
                                <td>{'}'}</td>
                            </tr>
                            <tr>
                                <td>\Uparrow</td>
                                <td>⇑</td>
                            </tr>
                            <tr>
                                <td>\Downarrow</td>
                                <td>⇓</td>
                            </tr>
                            <tr>
                                <td>/</td>
                                <td>/</td>
                            </tr>
                            <tr>
                                <td>\angle</td>
                                <td>∠</td>
                            </tr>
                            <tr>
                                <td>\lceil</td>
                                <td>⌈</td>
                            </tr>
                            <tr>
                                <td>\lfloor</td>
                                <td>⌊</td>
                            </tr>
                            <tr>
                                <td>\backslash</td>
                                <td>∖</td>
                            </tr>
                            <tr>
                                <td>\rangle</td>
                                <td>⟩</td>
                            </tr>
                            <tr>
                                <td>\rceil</td>
                                <td>⌉</td>
                            </tr>
                            <tr>
                                <td>\rfloor</td>
                                <td>⌋</td>
                            </tr>
                            <tr>
                                <td>\sin</td>
                                <td>sin</td>
                            </tr>
                            <tr>
                                <td>\cos</td>
                                <td>cos</td>
                            </tr>
                            <tr>
                                <td>\tan</td>
                                <td>tan</td>
                            </tr>
                            <tr>
                                <td>\cot</td>
                                <td>cot</td>
                            </tr>
                            <tr>
                                <td>\arcsin</td>
                                <td>arcsin</td>
                            </tr>
                            <tr>
                                <td>\arccos</td>
                                <td>arccos</td>
                            </tr>
                            <tr>
                                <td>\arctan</td>
                                <td>arctan</td>
                            </tr>
                            <tr>
                                <td>\arccot</td>
                                <td>arccot</td>
                            </tr>
                            <tr>
                                <td>\sinh</td>
                                <td>sinh</td>
                            </tr>
                            <tr>
                                <td>\cosh</td>
                                <td>cosh</td>
                            </tr>
                            <tr>
                                <td>\tanh</td>
                                <td>tanh</td>
                            </tr>
                            <tr>
                                <td>\coth</td>
                                <td>coth</td>
                            </tr>
                            <tr>
                                <td>\sec</td>
                                <td>sec</td>
                            </tr>
                            <tr>
                                <td>\csc</td>
                                <td>csc</td>
                            </tr>
                            <tr>
                                <td>\alpha</td>
                                <td>α</td>
                            </tr>
                            <tr>
                                <td>\beta</td>
                                <td>β</td>
                            </tr>
                            <tr>
                                <td>\gamma</td>
                                <td>γ</td>
                            </tr>
                            <tr>
                                <td>\Gamma</td>
                                <td>Γ</td>
                            </tr>
                            <tr>
                                <td>\delta</td>
                                <td>δ</td>
                            </tr>
                            <tr>
                                <td>\Delta</td>
                                <td>Δ</td>
                            </tr>
                            <tr>
                                <td>\epsilon</td>
                                <td>ϵ</td>
                            </tr>
                            <tr>
                                <td>\varepsilon</td>
                                <td>ε</td>
                            </tr>
                            <tr>
                                <td>\zeta</td>
                                <td>ζ</td>
                            </tr>
                            <tr>
                                <td>\eta</td>
                                <td>η</td>
                            </tr>
                            <tr>
                                <td>\theta</td>
                                <td>θ</td>
                            </tr>
                            <tr>
                                <td>\vartheta</td>
                                <td>ϑ</td>
                            </tr>
                            <tr>
                                <td>\Theta</td>
                                <td>Θ</td>
                            </tr>
                            <tr>
                                <td>\iota</td>
                                <td>ι</td>
                            </tr>
                            <tr>
                                <td>\kappa</td>
                                <td>κ</td>
                            </tr>
                            <tr>
                                <td>\Lambda</td>
                                <td>Λ</td>
                            </tr>
                            <tr>
                                <td>\lambda</td>
                                <td>λ</td>
                            </tr>
                            <tr>
                                <td>\mu</td>
                                <td>μ</td>
                            </tr>
                            <tr>
                                <td>\nu</td>
                                <td>ν</td>
                            </tr>
                            <tr>
                                <td>\xi</td>
                                <td>ξ</td>
                            </tr>
                            <tr>
                                <td>\Xi</td>
                                <td>Ξ</td>
                            </tr>
                            <tr>
                                <td>\pi</td>
                                <td>π</td>
                            </tr>
                            <tr>
                                <td>\Pi</td>
                                <td>Π</td>
                            </tr>
                            <tr>
                                <td>\rho</td>
                                <td>ρ</td>
                            </tr>
                            <tr>
                                <td>\varrho</td>
                                <td>ϱ</td>
                            </tr>
                            <tr>
                                <td>\sigma</td>
                                <td>σ</td>
                            </tr>
                            <tr>
                                <td>\Sigma</td>
                                <td>Σ</td>
                            </tr>
                            <tr>
                                <td>\tau</td>
                                <td>τ</td>
                            </tr>
                            <tr>
                                <td>\upsilon</td>
                                <td>υ</td>
                            </tr>
                            <tr>
                                <td>\Upsilon</td>
                                <td>Υ</td>
                            </tr>
                            <tr>
                                <td>\phi</td>
                                <td>ϕ</td>
                            </tr>
                            <tr>
                                <td>\varphi</td>
                                <td>φ</td>
                            </tr>
                            <tr>
                                <td>\Phi</td>
                                <td>Φ</td>
                            </tr>
                            <tr>
                                <td>\chi</td>
                                <td>χ</td>
                            </tr>
                            <tr>
                                <td>\psi</td>
                                <td>ψ</td>
                            </tr>
                            <tr>
                                <td>\Psi</td>
                                <td>Ψ</td>
                            </tr>
                            <tr>
                                <td>\omega</td>
                                <td>ω</td>
                            </tr>
                            <tr>
                                <td>\Omega</td>
                                <td>Ω</td>
                            </tr>
                            <tr>
                                <td>\partial</td>
                                <td>∂</td>
                            </tr>
                            <tr>
                                <td>\eth</td>
                                <td>ð</td>
                            </tr>
                            <tr>
                                <td>\hbar</td>
                                <td>ℏ</td>
                            </tr>
                            <tr>
                                <td>\imath</td>
                                <td>ı</td>
                            </tr>
                            <tr>
                                <td>\jmath</td>
                                <td>ȷ</td>
                            </tr>
                            <tr>
                                <td>\ell</td>
                                <td>ℓ</td>
                            </tr>
                            <tr>
                                <td>\Re</td>
                                <td>ℜ</td>
                            </tr>
                            <tr>
                                <td>\Im</td>
                                <td>ℑ</td>
                            </tr>
                            <tr>
                                <td>\wp</td>
                                <td>℘</td>
                            </tr>
                            <tr>
                                <td>\nabla</td>
                                <td>∇</td>
                            </tr>
                            <tr>
                                <td>\infty</td>
                                <td>∞</td>
                            </tr>
                            <tr>
                                <td>\aleph</td>
                                <td>ℵ</td>
                            </tr>
                            <tr>
                                <td>\beth</td>
                                <td>ℶ</td>
                            </tr>
                            <tr>
                                <td>\gimel</td>
                                <td>ℷ</td>
                            </tr>    
                        </tbody>
                    
                </table>
                : dropDown === 2 ?
                    <div className='drop-down' style={{top}}>
                        <div className='background-property'>
                            <label htmlFor='color-opacity' >Color opacity</label>
                            <input 
                                type='range' 
                                id='color-opacity'
                                min="0" 
                                max="100"
                                value={colorOpacity}
                                onChange={(e)=> {setColorOpacity(e.target.value)}}
                            />
                        </div>
                        <div className='background-property'>
                            <label htmlFor='background-opacity' >Background opacity</label>
                            <input 
                                type='range' 
                                id='background-opacity'
                                min="0" 
                                max="100"
                                value={backgroundOpacity}
                                onChange={(e)=> {setBackgroundOpacity(e.target.value)}}
                            />
                        </div>
                        <div className='background-property'>
                            <label htmlFor='background-url' ><FiLink /> </label>
                            <input 
                                type='url' 
                                id='background-url'
                                value={backgroundUrl}
                                placeholder='Background URL'
                                onChange={(e)=> {setBackgroundUrl(e.target.value)}}
                            />
                        </div>
                    </div>
                    : dropDown === 4 ?
                        <div className='drop-down drop-down-4' style={{top}}>
                            <div className='background-property'>
                                <label htmlFor='height' >Height</label>
                                <input 
                                    type='range' 
                                    id='height'
                                    min="100" 
                                    max="600"
                                    value={height}
                                    onChange={(e)=> {setHeight(e.target.value)}}
                                />
                            </div>
                            <div className='background-property'>
                                <label htmlFor='width' >Width</label>
                                <input 
                                    type='range' 
                                    id='width'
                                    min="100" 
                                    max="964"
                                    value={width}
                                    onChange={(e)=> {setWidth(e.target.value)}}
                                />
                            </div>
                        </div>
                        :''
                        
            }       
        </>
    )
}

export default DropDown;